services:
  client:
    build: ./client
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - server
  server:
    build: ./server
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/taskmanager
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-2025
      - NODE_ENV=development
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
